name: "my hello action"

description: "say hello with Github Actions"

inputs:
  firstGreeting:
    description: "A greeting."
    required: True
    default: "Moritz!"

  secondGreeting:
    description: "another person to greet"
    required: true
    default: "Mona the Octocat"

  thirdGreeting:
    description: "a third greeting"
    required: false

runs: 
  using: "docker"
  image: "Dockerfile"